server:
  port: 8080
spring:
  application:
    name: redbook-service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.227.200:8848
      config:
        server-addr: 192.168.227.200:8848
  config:
    import:
      - nacos:redbook-service-user.yaml
      - nacos:shared-config.yaml

