server:
  port: 10010
spring:
  application:
    name: redbook-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.227.200:8848
      config:
        server-addr: 192.168.227.200:8848
  config:
    import:
      - nacos:redbook-gateway.yaml